### ISSUE TITLE
With waitForInitialization on StatsigProvider - NextJS Head Does Not Render

### ISSUE THREAD

**Issue by GizmoRay** [statsig-io/react-sdk#11]
Hello Statsig team/community,
I run a marketing site and am using Statsig to run A/B/n tests on the website. I'm running into an issue where I'm calling the StatsigProvider in the _app.js file, with the waitForInitialization prop set to true, when I'm setting the metadata for a page with the Head component from NextJS, those values aren't ready in time for services like Facebook, Twitter, Slack, etc. to pick up that metadata. The result is all that data appears blank for those services, despite the code inspector in a browser showing they're working.

Toggling the waitForInitialization prop to false gets everything to work, however there is a FOUC as experiment data is initialized after page load.

Any ideas about how I should solve this?

Code snippets:

This does not work:
`
                 <StatsigProvider
                    sdkKey=KEY_HERE
                    waitForInitialization={true}
                  >
                <Component {...pageProps} />
                </StatsigProvider>
`

This does, but there is a flash of original content as the page loads:

`
                 <StatsigProvider
                    sdkKey=KEY_HERE
                    waitForInitialization={false}
                  >
                <Component {...pageProps} />
                </StatsigProvider>
`

Thanks,
Ben

**Comment by GizmoRay** [comment]
It's currently around the whole <Component> element in the _app.js page. The NextJS head tag would technically be within that element, AFAIK—I can try placing the Provider within the desired testing page, but per the docs the previous mode was the recommended approach.

I did see a blog post by Vercel that may solve some of these problems using Middleware and some of your other SDKs: https://vercel.com/blog/zero-cls-experiments-nextjs-edge-config

Is there general guidance from Statsig about the best approach for this?

Thanks,
Ben

**Comment by tore-statsig** [comment]
Oh the vercel integration is incredible - I definitely recommend that if youre using vercels edge config.  @joe-statsig  can expand on that.

The recommended approach is to wrap the entire portions of your app where you will be experimenting - so in this case, the body is probably sufficient.  It might require you to put the provider slightly lower down than the outer app.js

**Comment by tore-statsig** [comment]
Some additional docs on the vercel edge config integration

https://docs.statsig.com/integrations/vercel

**Comment by joe-statsig** [comment]
Hey @GizmoRay you can also try out the sample project for the edge config integration here: https://github.com/vercel/examples/tree/main/edge-middleware/ab-testing-statsig

**Comment by GizmoRay** [comment]
Ooh, these are both awesome resources! I'll check out both and see what works. Will close out this issue in the interim—really appreciate both of your help.

Thank you!
