### ISSUE TITLE
Add exposureLoggingDisabled Argument to useConfig, useExperiment, useGate, and useLayer Hooks

### ISSUE THREAD

**Issue by anthonybarsotti** [statsig-io/react-sdk#15]
For the `useConfig`, `useExperiment`, `useGate`, and `useLayer` hooks, it would be ideal if these allowed you to set the `exposureLoggingDisabled` value via an additional argument. We currently have to conditionally choose whether or not to use `useExperiment` or `useExperimentWithExposureLoggingDisabled` based on our users' cookie policy consent which looks something like this:

```ts
const userConsented: boolean = getUserConsent();
const useExperimentWithUserConsentPreference = userConsented
    ? useExperiment
    : useExperimentWithExposureLoggingDisabled;
// Have to type this as any to satisfy TS
const options: any = userConsented ? true : { keepDeviceValue: true };
const { config } = useExperimentWithUserConsentPreference(
  experimentName,
  options,
);
```

It would be ideal if we could just do this instead:

```ts
const userConsented: boolean = getUserConsent();
const { config } = useExperiment(
  experimentName,
  true, // keepDeviceValue
  false, // ignoreOverrides
  !userConsented, // Disable exposure logging for users who have denied tracking
);
```

**Comment by tore-statsig** [comment]
Those hooks should all be supported already
https://github.com/statsig-io/react-sdk/blob/main/src/index.ts#L35

**Comment by anthonybarsotti** [comment]
I don't think it would be a breaking change, that new argument would be optional and set to `false` by default so existing implementations wouldn't be impacted. If you want I could open a PR with what I have in mind.
