### ISSUE TITLE
useConfig has unstable results

### ISSUE THREAD

**Issue by samsch** [statsig-io/react-sdk#19]
`useConfig` called two times in a row should result in the same reference being returned.

What's expected:

```ts
const { config: config1 } = useConfig("config_name");
const { config: config2 } = useConfig("config_name");

config1 === config2 // true
```

What's actually happening is it's always false. `useConfig` passes a new object to `useConfigImpl` with every call that breaks the memoization of `useConfigImpl`, but also tried importing and calling `useConfigImpl` directly and that still resulted in different objects returned for each call.

**Comment by tore-statsig** [comment]
Yup, this is a bug and the root cause is exactly as you identified.  We will patch this shortly

**Comment by tore-statsig** [comment]
Actually, I think this won't quite work even with the fix.  The result of that check can be memoize across multiple renders (thats the bug), but back to back calls won't be memoized/give you the same result.  You really shouldnt need back to back calls though, just the memoization on future renders
