### ISSUE TITLE
Q: Why do useGate and useExperiment not accept an `exposureLoggingDisabled` param?

### ISSUE THREAD

**Issue by uriklar** [statsig-io/react-sdk#24]
We have some logic in our app where we'd like to conditionally log exposure according to some user related condition. 

My issue is that due to the rules of hooks, I can't conditionally call either `useExperiment` or `useExperimentWithExposureLoggingDisabled`. 

Now, I see that both hooks use the underlying `useExperimentImpl`, which accepts the `exposureLoggingDisabled` param. But, this param is not exposed in `useExperiment`. 

I can see the point in making your hooks explicit, but this makes it impossible to use them conditionally. Since the prop is supported, is there any issue with adding it as a prop to useExperiment (defaulting to false)? 

I'd be happy to create a PR but just wanted to check first if there's a technical reason for this choice as it looks intentional. 

Thanks!

**Comment by tore-statsig** [comment]
We really wanted the APIs to explicitly be separate, which was the primary reason.  We also didnt consider a conditional case - why is it that you only sometimes want to call with exposure logging disabled?  Typically, if you want to call with exposure logging disabled, you should always call with exposure logging disabled at that callsite, and log the exposure later.

That being said - we've made this exact change in the next big release of the react sdk coming soon - its a breaking change that you will have to migrate to, but the API is exactly what you've described.  Here is a [sample](https://github.com/statsig-io/js-client-monorepo/blob/main/samples/react/src/HomePage.tsx) and the `useExperiment` [hook that takes in options](https://github.com/statsig-io/js-client-monorepo/blob/main/packages/react-bindings/src/useExperiment.ts#L20) like `disableExposureLog`

For now, if you need to conditionally do this, you can always use the `useStatsig` hook, and conditionally call the `getExperiment` and `getExperimentWithExposureLoggingDisabled` methods on the `Statsig` singleton.

**Comment by uriklar** [comment]
Thanks! Glad to hear it's getting added 🙏 The reason for my conditional call is that our condition is according to a user type. So I wanted a single hook wrapping useExperiment which encapsulates this decision point. 

For now I'm just using `useExperimentWithExposureLoggingDisabled` and then calling `Statsig.manuallyLogExperimentExposure` for the specific user types we want to log. 

Does that make sense?

And thanks for the prompt response!

**Comment by tore-statsig** [comment]
Yeah that seems like the way to go for now.  Going to close this out as theres no additional action from our side at the moment. Thanks for the feedback!
