### ISSUE TITLE
type mismatch initializeValues

### ISSUE THREAD

**Issue by jonsan-ng** [statsig-io/react-sdk#4]
The `statsig-node` statsig. getClientInitializeResponse returns `Record<string, unknown> | null`
whereas the consumer StatSigSynchronousProvider is expecting `Record<string, unknown>`

**Comment by tore-statsig** [comment]
Being discussed elsewhere, but was intentional to force consumers of the API handle an edge case where their server SDK is initialized but has not fetched values from Statsig servers yet.

you can simply use:

```
initializeValues={statsig.getClientInitializeResponse(user) ?? {}}
```

To handle this case if you don't want to handle it differently.

**Comment by tore-statsig** [comment]
Closing as this isn't a true issue - the type mismatch was intentional and there are multiple ways to handle this case.  We will consider allowing a nullable `initializeValues` in the future, but this is not a blocking issue
