### ISSUE TITLE
Calling `Statsig.overrideGate` does not cause a re-render

### ISSUE THREAD

**Issue by jkalberer** [statsig-io/react-sdk#7]
There isn't an API on the `StatsigContext` and the recommended way to override gates is to use `Statsig.overrideGate`

Calling this API does not let the React context for Statsig know that there has been a change and that it should re-render. This means we have to do a manual redirect or something to trigger the re-render and get the overridden values to propagate.

The `Statsig` APIs need to change so that they trigger an update on the context for any mutation call (I'm not sure if there are other APIs that cause mutations).

**Comment by tore-statsig** [comment]
Thanks for the report, thats a great point!  We will look into fixing this

**Comment by tore-statsig** [comment]
Was resolved by the linked pr in Feb

**Comment by jkalberer** [comment]
Haha.. we noticed that it was fixed a while ago. Thanks @tore-statsig
